### ISSUE TITLE
播放声音(How to control the volume of Macast from handphone)

### ISSUE THREAD

**Issue by z-c-w** [xfangfang/Macast#12]
## Versions

- System version: (eg:11.4)
- Processor architecture: (eg:X86)
- APP version: (eg: v0.2)

## Problem

(投屏后播放声音是由电脑端控制还是手机端？建议手机端在投屏时显示「音量控制」)

**Comment by xfangfang** [comment]
目前的设定是：
操作系统控制声音的上限，Macast播放器在操作系统声音上限的基础上可以0-100调控声音。目前手机端是可以控制Macast播放器的声音的，国内的手机软件如：bilibili、网易云在投屏时直接调节手机音量都是可以控制Macast播放器声音的，但是确实有一些软件不支持控制声音，这是这些软件没有实现这个功能的缘故。

The operating system controls the upper limit of the volume. Based on the upper limit of the operating system volume, the Macast player can regulate the sound from 0 to 100. 
At present, the mobile client can control the sound of Macast player, but some software do not support sound control, which is because these software do not implement this function.

**Comment by xinyukk** [comment]
能不能直接电脑端控制声音呀，手机投屏之后手机声音必须调的很大才可以，很麻烦，

**Comment by xfangfang** [comment]
可以尝试以下快捷键 0和9

**Comment by limon** [comment]
能不能让播放器记住上次的音量，不然每开个视频又要调

**Comment by xfangfang** [comment]
> 能不能让播放器记住上次的音量，不然每开个视频又要调

现在支持配置默认声音大小啦，可以在配置文件中修改一下
