### ISSUE TITLE
[NEW FEATURE] history list at computer end

### ISSUE THREAD

**Issue by joshatt** [xfangfang/Macast#79]
Hi,

This app is so so great, please keep up the good work.
I want to ask for a new feature: a history list, especially including the time where every film was left off - I mean, when clicking a film in the history list, it will resume play at that time. With help of this app, we could watch tons of movies, but unfortunately we offten do not have full time to watch a movie, and this feature would come in handy.
I've tried the potplayer plugin, wondering if it's possible to resume history playback, but I failed to play any film, some certificate alert, looks like from internet explorer?

Thanks.

**Comment by xfangfang** [comment]
Video links in almost all apps are time-sensitive, so it will not be able to play after a period of time, which may be the reason why videos in the PotPlayer history list cannot be played.
Therefore the `history list` is meaningless, because most of the videos in the `history list` cannot be played.

**Comment by joshatt** [comment]
> Thank you for your advice.
> 
> Video links in almost all apps are time-sensitive, so it will not be able to play after a period of time, which may be the reason why videos in the PotPlayer history list cannot be played. Therefore the `history list` is meaningless, because most of the videos in the `history list` cannot be played.

Thanks for the info. Have a good one.
